apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
      spec:
        template:
          spec:
            tolerations:
              - key: "node.cloudprovider.kubernetes.io/uninitialized"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
      spec:
        template:
          spec:
            tolerations:
              - key: "node.cloudprovider.kubernetes.io/uninitialized"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-controller
      spec:
        template:
          spec:
            tolerations:
              - key: "node.cloudprovider.kubernetes.io/uninitialized"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
      spec:
        template:
          spec:
            tolerations:
              - key: "node.cloudprovider.kubernetes.io/uninitialized"
                operator: "Equal"
                value: "true"
                effect: "NoSchedule"
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux